import Head from "next/head";
import { GetServerSideProps } from "next";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

export type ProductProps = {
  id: string | number;
};

export default function Home({ id }: ProductProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Product page</h1>
      <h2>ID: {id}</h2>
      <Link href="/">To Home</Link>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const id = context.params?.id;

  return { props: { id } };
};
